version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgresql
    ports:
      - 5433:5432
    environment: 
      ### This environment variable sets the superuser password for PostgreSQL. The default superuser is defined by the POSTGRES_USER environment variable.
      POSTGRES_PASSWORD: passpass
      ### This optional environment variable is used in conjunction with POSTGRES_PASSWORD to set a user and its password. This variable will create the specified user with superuser power and a database with the same name. If it is not specified, then the default user of postgres will be used.
      POSTGRES_USER: admin
      ### This optional environment variable can be used to define a different name for the default database that is created when the image is first started. If it is not specified, then the value of POSTGRES_USER will be used.
      POSTGRES_DB: sylphrena
      #### Note: The PostgreSQL image uses several others environment variables, you can find them in the follow link: https://hub.docker.com/_/postgres
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local