version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysql
    volumes:
      - db:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      ### This variable is mandatory and specifies the password that will be set for the MySQL root superuser account.
      MYSQL_ROOT_PASSWORD: password
      ### This variable is optional and allows you to specify the name of a database to be created on image startup. If a user/password was supplied (see below) then that user will be granted superuser access (corresponding to GRANT ALL) to this database.
      MYSQL_DATABASE: roshar
      ### These variables are optional, used in conjunction to create a new user and to set that user's password. This user will be granted superuser permissions (see above) for the database specified by the MYSQL_DATABASE variable. Both variables are required for a user to be created. Do note that there is no need to use this mechanism to create the root superuser, that user gets created by default with the password specified by the MYSQL_ROOT_PASSWORD variable.
      MYSQL_USER: shallan
      MYSQL_PASSWORD: pattern
volumes:
  db:
    driver: local